name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.1"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install django
      - name: Run server
        run: |
          django manage.py runserver
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest mysite/polls/tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true